source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

# Database
gem 'pg', '~> 0.19.0'
# Use Puma as the app server
gem 'puma', '~> 3.0'

# Password Encryption
gem 'bcrypt', '~> 3.1', '>= 3.1.11'

# Faker for generating test data
gem 'faker', '~> 1.6', '>= 1.6.6'

gem 'rack-cors', '~> 0.4.0'

gem 'simplecov', '~> 0.12.0', require: false, group: :test

group :development, :test do
  # Call 'byebug' anywhere in the code
  # to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # Use RSpec for specs
  gem 'rspec-rails', '>= 3.5.0'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.1'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
